# Generated by Django 5.2.17 on 2026-08-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('extracted_requirements', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True)),
                ('redacted_text', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_experience', models.JSONField(blank=True, default=list)),
                ('extracted_education', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_subscore', models.FloatField(default=0)),
                ('experience_subscore', models.FloatField(default=0)),
                ('education_subscore', models.FloatField(default=0)),
                ('skills_justification', models.TextField(blank=True)),
                ('experience_justification', models.TextField(blank=True)),
                ('education_justification', models.TextField(blank=True)),
                ('evidence_quotes', models.JSONField(blank=True, default=dict)),
                ('deterministic_score', models.FloatField(default=0)),
                ('llm_semantic_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('interview_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='screener.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='screener.resume')),
            ],
            options={
                'ordering': ['-final_score'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
    ]
