# Generated by Django 5.2.17 on 2026-08-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_match_eligibility_details_match_is_eligible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='skill_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
