# Generated by Django 5.2.17 on 2026-08-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_match_skill_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
