# Generated by Django 5.2.17 on 2026-08-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_jobdescription_status_match_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uploaded_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_uploaded_resumes', to='screener.jobdescription'),
        ),
    ]
